import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import SessionProvider, {
  CartMergeOnLogin,
} from "~/components/SessionProvider";
import { auth } from "~/lib/auth";
import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/Header/Header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="fr">
      <body className={geist.className}>
        <SessionProvider session={session}>
          <TRPCReactProvider>
            <Header />
            <CartMergeOnLogin />
            {children}
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
